version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Você pode definir variáveis de ambiente aqui, se necessário.
      - ENVIRONMENT=production
      - DEBUG=False
    volumes:
      - .:/app