name: meu_ambiente
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask>=2.0.0
  - kivy>=2.0.0
  - python-dotenv>=0.15.0
# conda env update --name meu_ambiente --file environment.yml --prune